config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"

  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]


  resources :users, only: [:index, :create, :show, :edit, :update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, uniqueness: true, length: {minimum: 2, maximum: 20 }
  validates :introduction, length: {maximum: 50 }

  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize: size).processed
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def create
    @book = Book.new(book_params)
    @books = Book.all
    @user = current_user
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end

    private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @book = Book.new
    @users = User.all
    @user_new = current_user
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_info.html.erb
  <div class="col-md-3">
      <h2>User info</h2>
　　　　　<%= image_tag user.get_profile_image("63x63") %>
  　　　　　　<table class="table">
    　　　　　　<tbody>
  　　　　　　　　　　<tr>
                <th>name</th>
                <th><%= user.name %></th>
              </tr>
              <tr>
                <th>introduction</th>
                <th><%= user.introduction %></th>
              </tr>
            </tbody>
          </table>

        <div class="row">
         <% if user == current_user %>
           <%= link_to edit_user_path(current_user), class: 'btn btn-outline-secondary btn-block' do %>
             <i class="fas fa-user-cog"></i>
           <% end %>
         <% else %>
           <%= link_to edit_user_path(user), class: 'btn btn-outline-secondary btn-block' do %>
             <i class="fas fa-user-cog"></i>
           <% end %>
         <% end %>
       </div>

      <h2 class="mt-3">New book</h2>
      <%= form_with model: book, local:true do |f| %>
        <p>Title</p>
        <%= f.text_field :title %>
        <p>Opinion</p>
        <%= f.text_area :body %><br>
        <%= f.submit "Create Book", class: 'btn btn-success' %>
      <% end %>
    </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>

      <% if @book.errors.any? %>
        <div class="error">
        <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
           <% end %>
        </ul>
        </div>
      <% end %>


      <%= form_with model: @book, local: true do |f| %>
          <div class="form-group">
            <p>Title</p>
            <%= f.text_field :title %>
          </div>

          <div class="form-group">
            <p>Opinion</p>
            <%= f.text_area :body %><br>
          </div>

          <div class="form-group">
            <%= f.submit 'Update Book', class: 'btn btn-success' %>
          </div>
      <% end %>

      <%= link_to "Show", book_path(@book.id) %> |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
    <% if @book.errors.any? %>
    <div class="error">
    <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    </div>
    <% end %>


<div class="row">
<%= render 'books/info', {book: @book, user: @user} %>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <% @books.each do |book| %>
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag book.user.get_profile_image("40x40") %>
                <% end %>
              </td>
              <td><%= link_to book.title,"/books/#{book.id}" %></td>
              <td><%= book.body %></td>
            </tr>
          </tbody>
          <% end %>
        </table>
      </div>
  </div>

app/views/books/show.html.erb
<div class="row">
<%= render 'books/info', {book: @new_book, user: @book.user} %>

  <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table">
      <tbody>
        <tr>
          <td>
            <%= link_to user_path(@book.user) do %>
              <%= image_tag @book.user.get_profile_image("40x40") %><br>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title %></td>
          <td><%= @book.body %></td>
        <% if @book.user == current_user %>
          <td>
            <%= link_to "Edit", edit_book_path(@book.id), class: 'btn btn-sm btn-success' %>
          </td>
          <td>
            <%= link_to "Destroy", book_path(@book), method: :delete, class: 'btn btn-sm btn-danger', "data-confirm" => "本当に消しますか？" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/homes/about.html.erb
<div class="row">
  <h1 class="px-3 mx-auto">Welcome to
  <i class="fas fa-book"></i>
  <strong>Bookers</strong>
  !</h1>
</div>

app/views/homes/top.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>!!</h1>
      <p>In <i class="fas fa-book"></i>
      <strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
            <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3' %>
            <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <li class="navbar-nav">
            <%= link_to "Bookers", root_path, class: 'nav-link text-light' %>
          </li>
          <ul class="navbar-nav ml-auto">

          <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i>
              Home
            <% end %>
          </li>
          <li>
            <%= link_to users_path, class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i>
              Users
          <% end %>
          </li>
          <li>
            <%= link_to books_path, class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i>
              Books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i>
              Log out
            <% end %>
          </li>
          <% else %>
          <li>
            <%= link_to root_path, class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i>
              Home
            <% end %>
          </li>
          <li>
            <%= link_to about_path, class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i>
              About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i>
              Sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i>
              Log in
            <% end %>
          </li>
          <% end %>
          </ul>
        </div>
      </div>
      </nav>
    </header>

    <main>
      <p class="notice"><%= flash[:notice] %></p>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <% if @user.errors.any? %>
        <div class="error">
        <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
        </div>
      <% end %>

      <%= form_with model: @user, local:true do |f| %>
        <label for="inputName">Name</label><br>
        <%= f.text_field :name, autofocus: true, id:"inputName" %><br>
        <label for="inputImage">Image</label><br>
        <%= f.file_field :profile_image, accept: "image/*" %><br>
        <label for="inputIntroduction">Introduction</label><br>
        <%= f.text_area :introduction %><br>
        <%= f.submit "Update User", class: 'btn btn-secondary' %><br>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
<%= render 'books/info', {book: @book, user: @user_new} %>

<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% @users.each do |user| %>
  <tbody>
    <tr>
      <td><%= image_tag user.get_profile_image("40x40") %></td>
      <td><%= user.name %></td>
      <td>
        <%= link_to "Show", user_path(user.id) %>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>
</div>

</div>

app/views/users/show.html.erb
<div class="row">
<%= render 'books/info', {book: @book, user: @user} %>

    <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <% @books.each do |book| %>
            <tbody>
                <tr>
                  <td>
                    <%= link_to user_path(book.user) do %>
                      <%= image_tag book.user.get_profile_image("40x40") %>
                    <% end %>
                  </td>
                  <td><%= link_to book.title,"/books/#{book.id}" %></td>
                  <td><%= book.body %></td>
                </tr>
            </tbody>
            <% end %>
        </table>
    </div>
 </div>